version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: mancom_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mancom
    ports:
      - "5432:5432"
    volumes:
      - mancom_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  mancom_pgdata:
